deploy:
  needs: test
  runs-on: ubuntu-latest

  if: github.ref == 'refs/heads/main'

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node dependencies & build assets
      run: |
        npm install
        npm run build

    - name: FTP Deploy to Hostibro
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /task.digistat.shop/
        exclude: |
          **/.git*
          **/.github*
          **/node_modules/**
          **/tests/**
          .env